name: TypeScript Type Check

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  type-check:
    name: Type Check
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run TypeScript type checking
        run: npm run type-check:ci

      - name: Run strict type checking (allowed to fail)
        run: npm run type-check:strict || echo "Strict type checking failed but continuing..."
        continue-on-error: true

      - name: Upload type check results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: type-check-results-${{ matrix.node-version }}
          path: |
            typescript-errors.log
            tsconfig.tsbuildinfo
          retention-days: 7
